### PR TITLE
Feature/pickaxe tags

### LINKED ISSUE #5: Allow Pickaxe to Harvest Cobblegens Faster
It would be nice if the cobblegens could be harvested faster with a pickaxe, as it's pretty slow at the moment.

### PR DESCRIPTION
**Pull request by MelanX**
This allows to mine the blocks faster when using a pickaxe. This resolves #5.
This PR also includes #22. I separated these two things in case you don't want the tags.

### CODE REVIEW

**Comment by LexManos** [comment]
This update looks fine, just waiting for Orion to PR a change to use  our new TC build server.

**Comment by MelanX** [comment]
Updated to match master branch

**Comment by LexManos** [comment]
To be clear, the only functional change this does, is create the ```{
  "values": [
    "cobblefordays:tier_1",
    "cobblefordays:tier_2",
    "cobblefordays:tier_3",
    "cobblefordays:tier_4",
    "cobblefordays:tier_5"
  ]
}``` tag.
Which.. you can do in your own data packs. 
The rest of this change is not going in as its churn for churns sake.

**Comment by MelanX** [comment]
Yes, this pr was mainly to resolve #5. If you don’t want to provide in on your own, it’s ok.

**Pull request closed without merging**
